### ISSUE TITLE
minimal pheno: invalid birth dates

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/finregistry-data#15]
Minimal phenotype contains 10 invalid birth dates. All are 29.2. for years that are not leap years. 

```
path = "(path to minimal phenotype)"
df = fread(path, select = c("FINREGISTRYID", "date_of_birth"))
dates = dmy(birth_dat$date_of_birth)
# Warning message: 10 failed to parse.
df[is.na(dates)]
```

**Comment by pecsimax** [comment]
implemented in release https://github.com/dsgelab/finregistry-data/releases/tag/minimal_phenotype_2023-05-02
